apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-deployment-<place_name>
  labels:
    version: 0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radar-deployment-<place_name>
      version: 0.2
  template:
    metadata:
      labels:
        run: radar-deployment-<place_name>
        version: 0.2
    spec:
      initContainers:
      - name: package-installer
        image: python:3.8-alpine
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            apk add git
            rm -rf /tmp/git-download/script
            git clone $GIT_REPOSITORY /tmp/git-download/script
        env:
        - name: GIT_REPOSITORY
          value: https://github.com/cchou0519/crawler.git
        volumeMounts:
        - mountPath: /tmp/git-download
          name: git-download
      containers:
      - name: executor
        image: selenium/standalone-chrome-debug:3.141.59-20210607
        ports:
          - containerPort: 4444
          - containerPort: 5900
        volumeMounts:
          - mountPath: /dev/shm
            name: cache-volume
      - name: web-driver
        image: amancevice/pandas:1.4.2-alpine
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            apk add --update --no-cache --virtual .tmp-build-deps \
                              gcc libc-dev linux-headers postgresql-dev \
                              && apk add libffi-dev
            pip install selenium requests pytz pygsheets
            cd /tmp/git-download/script/pokemon
            python main.py
        env:
          - name: REMOTE_EXECUTOR
            value: "http://localhost:4444/wd/hub"
          - name: INIT_LAT
            valueFrom:
              configMapKeyRef:
                name: my-cfmp
                key: <place_name>_LAT
          - name: INIT_LON
            valueFrom:
              configMapKeyRef:
                name: my-cfmp
                key: <place_name>_LON
          - name: LINE_TOKEN
            valueFrom:
              configMapKeyRef:
                name: my-cfmp
                key: <place_name>_LINE_TOKEN
          - name: ZOOM_OUT_TIMES
            value: <zoom_out_times>
          - name: IS_100
            value: <is_100>
          - name: IS_PVP
            value: <is_pvp>
        volumeMounts:
          - mountPath: /tmp/git-download
            name: git-download
          - mountPath: /tmp/git-download/script/pokemon/config/google-sheet-key.json
            name: my-google-token
            subPath: google-key.json
      restartPolicy: Always
      volumes:
      - name: git-download
        emptyDir: {}
      - name: my-google-token
        configMap:
          name: my-google-token
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: 1024Mi
