apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-deployment-taipei
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radar-deployment-taipei
  template:
    metadata:
      labels:
        run: radar-deployment-taipei
    spec:
      initContainers:
      - name: package-installer
        image: python:3.8-alpine
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            apk add git
            git clone $GIT_REPOSITORY /tmp/git-download/script
        env:
        - name: GIT_REPOSITORY
          value: https://github.com/cchou0519/crawler.git
        volumeMounts:
        - mountPath: /tmp/git-download
          name: git-download
      containers:
      - name: executor
        image: selenium/standalone-chrome-debug:3.141.59-20210607
        ports:
          - containerPort: 4444
          - containerPort: 5900
        volumeMounts:
          - mountPath: /dev/shm
            name: cache-volume
      - name: web-driver
        image: python:3.8-alpine
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            apk add --update --no-cache --virtual .tmp-build-deps \
                              gcc libc-dev linux-headers postgresql-dev \
                              && apk add libffi-dev
            pip install selenium requests pytz pygsheets
            cd /tmp/git-download/script
            python main.py
        env:
          - name: REMOTE_EXECUTOR
            value: "http://localhost:4444/wd/hub"
          - name: INIT_LAT
            valueFrom:
              configMapKeyRef:
                name: my-cfmp
                key: HC_LAT
          - name: INIT_LON
            valueFrom:
              configMapKeyRef:
                name: my-cfmp
                key: HC_LON
          - name: LINE_TOKEN
            valueFrom:
              configMapKeyRef:
                name: my-cfmp
                key: HC_LINE_TOKEN
        volumeMounts:
          - mountPath: /tmp/git-download
            name: git-download
          - mountPath: /tmp/git-download/script/pokemon/config/google-key.json
            name: my-google-token
            subPath: google-key.json
      restartPolicy: Always
      volumes:
      - name: git-download
        emptyDir: {}
      - name: my-cfmp
        configMap:
          name: my-cfmp
      - name: my-google-token
        configMap:
          name: my-google-token
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: 2048Mi

